config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users
  patch "/locale", to: "users#update_locale", as: :update_locale

  # devise_for :users, controllers: {
  #   confirmations: "users/confirmations"
  # }

  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  resources :lalas do
    collection do
      get :card_transactions
      get :card_transactions_month_year

      get :cash_transactions
      get :cash_transactions_month_year
    end
  end

  resources :pages, only: :index do
    collection do
      get :donation
      get :notification
    end
  end

  resources :user_cards, except: :show
  resources :user_bank_accounts, except: :show
  resources :categories, except: :show
  resources :entities, except: :show
  resources :balances, only: :index do
    get :json, on: :collection
  end

  resources :cash_transactions, except: :show do
    collection do
      get :month_year
      get :inspect
    end
  end

  resources :card_transactions, except: :show do
    member do
      get :duplicate
    end

    collection do
      get :month_year
      get :search
      post :pay_in_advance
    end
  end

  resources :cash_installments, only: [] do
    member do
      patch :pay
    end

    collection do
      post :pay_multiple
    end
  end

  resources :investments, except: :show do
    collection do
      get :month_year
    end
  end

  resources :budgets, except: :show do
    collection do
      get :month_year
    end
  end

  namespace :admin do
    get :data_backup, to: "backups#data_backup"
  end

  root "pages#index"
end

app/models/user_card.rb
# frozen_string_literal: true

class UserCard < ApplicationRecord
  # @extends ..................................................................
  # @includes .................................................................
  include HasActive

  # @security (i.e. attr_accessible) ..........................................
  # @relationships ............................................................
  belongs_to :user
  belongs_to :card

  has_many :card_transactions
  has_many :card_installments, through: :card_transactions
  has_many :card_installments_invoices, lambda {
    joins(:categories).where(categories: { category_name: "CARD PAYMENT" }).distinct
  }, through: :card_installments, source: :cash_transaction

  has_many :cash_transactions

  has_many :references, dependent: :destroy

  # @validations ..............................................................
  validates :user_card_name, :due_date_day, :days_until_due_date, :min_spend, :credit_limit, presence: true
  validates :user_card_name, uniqueness: { scope: %i[user_id card_id] }

  # @callbacks ................................................................
  before_validation :set_user_card_name, on: :create
  after_update :update_references_and_payments, if: :payment_date_settings_changed?

  # @scopes ...................................................................
  # @additional_config ........................................................
  # @class_methods ............................................................
  # @public_instance_methods ..................................................
  def find_or_create_reference_for(date)
    reference_date = calculate_reference_date(date)
    reference = references.find_by(month: reference_date.month, year: reference_date.year)
    return reference if reference.present?

    references.create(
      month: reference_date.month,
      year: reference_date.year,
      reference_closing_date: reference_date - days_until_due_date.days,
      reference_date:
    )
  end

  def calculate_reference_date(transaction_date)
    due_date = transaction_date.change(day: due_date_day)
    due_date = (due_date + 1.month) if transaction_date >= due_date
    closing_date = due_date - days_until_due_date.days

    return due_date if closing_date > transaction_date

    due_date + 1.month
  end

  # @protected_instance_methods ...............................................

  protected

  # Sets `user_card_name` in case it was not previously set, on create.
  #
  # @note This is a method that is called before_validation.
  #
  # @return [void].
  #
  def set_user_card_name
    self.user_card_name ||= card.card_name
  end

  # @private_instance_methods .................................................

  private

  def payment_date_settings_changed?
    saved_change_to_due_date_day? || saved_change_to_days_until_due_date?
  end

  def update_references_and_payments
    month_years = card_installments_invoices.pluck(:month, :year).uniq

    month_years.each do |month, year|
      next if references.exists?(month:, year:)

      card_payment = card_installments_invoices.find_by(month:, year:)
      next if card_payment.nil?

      references.create(
        month:,
        year:,
        reference_closing_date: card_payment.date - days_until_due_date.days,
        reference_date: card_payment.date
      )
    end
  end
end

# == Schema Information
#
# Table name: user_cards
#
#  id                      :bigint           not null, primary key
#  active                  :boolean          default(TRUE), not null
#  card_transactions_count :integer          default(0), not null
#  card_transactions_total :integer          default(0), not null
#  credit_limit            :integer          not null
#  days_until_due_date     :integer          not null
#  due_date_day            :integer          default(1), not null
#  min_spend               :integer          not null
#  user_card_name          :string           not null, uniquely indexed => [user_id, card_id]
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  card_id                 :bigint           not null, indexed, uniquely indexed => [user_id, user_card_name]
#  user_id                 :bigint           not null, uniquely indexed => [card_id, user_card_name], indexed
#
# Indexes
#
#  index_user_cards_on_card_id           (card_id)
#  index_user_cards_on_on_composite_key  (user_id,card_id,user_card_name) UNIQUE
#  index_user_cards_on_user_id           (user_id)
#

app/controllers/user_cards_controller.rb
# frozen_string_literal: true

class UserCardsController < ApplicationController
  include TabsConcern
  include ContextHelper

  before_action :set_user_card, only: %i[edit update destroy]
  before_action :set_cards, :set_user_cards, :set_entities, :set_categories, only: %i[new create edit update]

  def index
    params[:include_inactive] ||= "false"
    conditions = { active: [ true, !JSON.parse(params[:include_inactive]) ] }

    @user_cards = Logic::UserCards.find_by(current_user, conditions)

    respond_to do |format|
      format.html

      format.turbo_stream do
        set_tabs(active_menu: :basic, active_sub_menu: :user_card)
      end
    end
  end

  def new
    @user_card = current_user.user_cards.new

    respond_to do |format|
      format.html
      format.turbo_stream do
        set_tabs(active_menu: :basic, active_sub_menu: :user_card) if params[:no_user_card]
      end
    end
  end

  def create
    index
    @user_card = Logic::UserCards.create(user_card_params)

    if @user_card.active?
      @card_transaction = Logic::CardTransactions.create_from(user_card: @user_card) if @user_card.valid?

      if @card_transaction
        set_user_cards
        set_tabs(active_menu: :card, active_sub_menu: @user_card&.user_card_name)
      end
    end

    respond_to(&:turbo_stream)
  end

  def edit; end

  def update
    index
    @user_card = Logic::UserCards.update(@user_card, user_card_params)

    if @user_card.active?
      @card_transaction = Logic::CardTransactions.create_from(user_card: @user_card) if @user_card.valid?

      if @card_transaction
        set_user_cards
        set_tabs(active_menu: :card, active_sub_menu: @user_card&.user_card_name)
      end
    end

    respond_to(&:turbo_stream)
  end

  def destroy
    @user_card.destroy if @user_card.card_transactions.empty?
    set_tabs(active_menu: :basic, active_sub_menu: :user_card)
    index

    respond_to(&:turbo_stream)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user_card
    @user_card = current_user.user_cards.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_card_params
    ret_params = params.require(:user_card)
    if ret_params[:current_closing_date].present? && ret_params[:current_due_date].present?
      ret_params[:due_date_day]        = ret_params[:current_due_date].to_date.day
      ret_params[:days_until_due_date] = ret_params[:current_due_date].to_date - ret_params[:current_closing_date].to_date
    end

    ret_params.permit(:user_card_name, :due_date_day, :days_until_due_date, :min_spend, :credit_limit, :active, :user_id, :card_id)
  end
end

app/views/user_cards/user_card/_mobile_user_card.html.erb
<%= content_tag :div, class: "rounded-lg shadow-sm overflow-hidden my-3 bg-slate-100", data: { id: user_card.id, datatable_target: :row } do %>
  <div class="p-4 bg-gradient-to-r from-blue-500 to-blue-700">
    <div class="flex items-center justify-between">
      <div class="flex items-center space-x-3">
        <%= render_icon :credit_card %>
        <% brand_name = user_card.card.card_name %>
        <% brand_and_name = brand_name == user_card.user_card_name ? brand_name : "#{brand_name} - #{user_card.user_card_name}" %>

        <%= link_to brand_and_name,
                    edit_user_card_path(user_card),
                    id: "edit_user_card_#{user_card.id}",
                    class: "text-lg font-semibold text-black underline underline-offset-[3px]",
                    data: { turbo_frame: :center_container } %>
      </div>

      <%= link_to card_transactions_path(user_card_id: user_card.id, format: :turbo_stream), data: { turbo_frame: :center_container } do %>
        <%= render_icon :jump_to %>
      <% end %>
    </div>
  </div>

  <div class="p-4">
    <div class="grid grid-cols-2 gap-4 my-2">
      <div class="space-y-1">
        <div class="flex items-center space-x-2">
          <%= render_icon :number %>
          <%= content_tag :span, pluralise_model(CardTransaction, 2), class: "text-sm font-medium text-slate-500" %>
        </div>

        <div class="flex items-center">
          <%= content_tag :span, user_card.card_transactions_count, class: "text-sm font-semibold text-slate-800" %>
        </div>
      </div>

      <div class="space-y-1">
        <div class="flex items-center space-x-2">
          <%= render_icon :money %>
          <%= content_tag :span, model_attribute(CardTransaction, :total_amount), class: "text-sm font-medium text-slate-500" %>
        </div>

        <div class="flex items-center">
          <%= content_tag :span, from_cent_based_to_float(user_card.card_transactions_total, "R$"), class: "text-sm font-semibold text-slate-800 mr-auto" %>
        </div>
      </div>
    </div>

    <div class="grid grid-cols-2 gap-4 my-2">
      <div class="space-y-1">
        <div class="flex items-center space-x-2">
          <%= render_icon :calendar %>
          <%= content_tag :span, model_attribute(UserCard, :current_closing_date), class: "text-sm font-medium text-slate-500" %>
        </div>

        <div class="flex items-center">
          <%= content_tag :span, l(Date.current.change(day: user_card.due_date_day) - user_card.days_until_due_date, format: :short) %>
        </div>
      </div>

      <div class="space-y-1">
        <div class="flex items-center space-x-2">
          <%= render_icon :calendar %>
          <%= content_tag :span, model_attribute(UserCard, :current_due_date), class: "text-sm font-medium text-slate-500" %>
        </div>

        <div class="flex items-center">
          <%= content_tag :span, l(Date.current.change(day: user_card.due_date_day), format: :short) %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/user_cards/user_card/_user_card.html.erb
<%= content_tag :div,
                class: "grid grid-cols-9 gap-2 border-b border-slate-200 #{cycle('bg-gray-100', 'bg-gray-200')} hover:bg-white",
                data: { id: user_card.id, datatable_target: :row } do %>

    <div class="col-span-2 px-1 flex items-center mx-auto font-lekton font-semibold">
      <% brand_name = user_card.card.card_name  %>
      <% brand_and_name = brand_name == user_card.user_card_name ? brand_name : "#{brand_name} - #{user_card.user_card_name}" %>
      <%= content_tag :span, brand_and_name, class: "px-4 whitespace-nowrap" %>
    </div>

    <div class="jump_to_card_transactions px-1 flex items-center justify-center mx-auto font-anonymous font-semibold whitespace-nowrap ml-auto">
      <% if user_card.card_transactions_count > 0 %>
        <%= link_to user_card.card_transactions_count,
                    card_transactions_path(user_card_id: user_card.id, format: :turbo_stream),
                    class: "text-indigo-600 hover:underline",
                    data: { turbo_frame: :center_container, turbo_prefetch: false } %>
      <% else %>
        <%= content_tag :span, user_card.card_transactions_count %>
      <% end %>
    </div>

    <div class="flex items-center justify-center text-lg whitespace-nowrap ml-auto">
      <%= content_tag :span, from_cent_based_to_float(user_card.card_transactions_total, "R$") %>
    </div>


    <div class="flex items-center justify-center text-lg whitespace-nowrap ml-auto pr-2 border-r border-black">
      <%= content_tag :span, l(Date.current.change(day: user_card.due_date_day) - user_card.days_until_due_date, format: :shorter), class: "current_closing_date" %>
    </div>

    <div class="flex items-center justify-center text-lg whitespace-nowrap mr-auto">
      <%= content_tag :span, l(Date.current.change(day: user_card.due_date_day), format: :shorter), class: "current_due_date" %>
    </div>

    <div class="flex items-center justify-center font-lekton text-lg whitespace-nowrap ml-auto">
      <%= content_tag :span, from_cent_based_to_float(user_card.min_spend, "R$") %>
    </div>

    <div class="flex items-center justify-center font-lekton text-lg whitespace-nowrap ml-auto">
      <%= content_tag :span, from_cent_based_to_float(user_card.credit_limit, "R$") %>
    </div>

    <div class="flex items-center justify-center">
      <div class="flex items-center justify-center px-2 my-1 rounded-md">
        <%= link_to edit_user_card_path(user_card),
                    id: "edit_user_card_#{user_card.id}",
                    class: "text-blue-600 hover:text-blue-800 mx-2 bg-sky-200 rounded-4xl",
                    data: { turbo_frame: :center_container } do %>
          <%= render_icon :pencil %>
        <% end %>

        <%= link_to user_card,
                    id: "delete_user_card_#{user_card.id}",
                    class: "text-red-600 hover:text-red-800 mx-2 bg-rose-200 rounded-4xl",
                    data: { turbo_method: :delete, turbo_confirm: t("confirmation.sure") } do %>
          <%= render_icon :destroy %>
        <% end %>
      </div>
    </div>
  <% end %>