config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users
  patch "/locale", to: "users#update_locale", as: :update_locale

  # devise_for :users, controllers: {
  #   confirmations: "users/confirmations"
  # }

  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  resources :lalas do
    collection do
      get :card_transactions
      get :card_transactions_month_year

      get :cash_transactions
      get :cash_transactions_month_year
    end
  end

  resources :pages, only: :index do
    collection do
      get :donation
      get :notification
    end
  end

  resources :user_cards, except: :show
  resources :user_bank_accounts, except: :show
  resources :categories, except: :show
  resources :entities, except: :show
  resources :balances, only: :index do
    get :json, on: :collection
  end

  resources :cash_transactions, except: :show do
    collection do
      get :month_year
      get :inspect
    end
  end

  resources :card_transactions, except: :show do
    member do
      get :duplicate
    end

    collection do
      get :month_year
      get :search
      post :pay_in_advance
    end
  end

  resources :cash_installments, only: [] do
    member do
      patch :pay
    end

    collection do
      post :pay_multiple
    end
  end

  resources :investments, except: :show do
    collection do
      get :month_year
    end
  end

  resources :budgets, except: :show do
    collection do
      get :month_year
    end
  end

  namespace :admin do
    get :data_backup, to: "backups#data_backup"
  end

  root "pages#index"
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  # @extends ..................................................................
  # @includes .................................................................
  include HasActive
  include TranslateHelper

  # @security (i.e. attr_accessible) ..........................................
  # @relationships ............................................................
  belongs_to :user

  has_many :category_transactions, dependent: :destroy
  has_many :card_transactions, through: :category_transactions, source: :transactable, source_type: "CardTransaction"
  has_many :cash_transactions, through: :category_transactions, source: :transactable, source_type: "CashTransaction"
  has_many :investments, through: :category_transactions, source: :transactable, source_type: "Investment"

  # @validations ..............................................................
  validates :category_name, presence: true, uniqueness: { scope: :user_id }
  validates :colour, presence: true
  validates :built_in, inclusion: { in: [ true, false ] }

  # @callbacks ................................................................
  before_validation :set_built_in

  # @scopes ...................................................................
  scope :built_in, -> { where(built_in: true) }

  # @additional_config ........................................................
  # @class_methods ............................................................
  # @public_instance_methods ..................................................

  # @return [Boolean].
  #
  def built_in?
    built_in
  end

  def bg_colour
    COLOURS.dig(colour, :bg)
  end

  def from_bg
    COLOURS.dig(colour, :from)
  end

  def via_bg
    COLOURS.dig(colour, :via)
  end

  def to_bg
    COLOURS.dig(colour, :to)
  end

  def text_colour
    COLOURS.dig(colour, :text)
  end

  def name
    return model_attribute(self, attributes["category_name"].parameterize(separator: "_")).upcase if built_in?

    attributes["category_name"]
  end

  def update_card_transactions_count_and_total
    update_columns(card_transactions_count: card_transactions.count, card_transactions_total: card_transactions.sum(:price))
  end

  def update_cash_transactions_count_and_total
    update_columns(cash_transactions_count: cash_transactions.count, cash_transactions_total: cash_transactions.sum(:price))
  end

  # @protected_instance_methods ...............................................

  protected

  # Sets `built_in` in case it was not previously set.
  #
  # @note This is a method that is called before_validation.
  #
  # @return [void].
  #
  def set_built_in
    self.built_in ||= false
  end

  # @private_instance_methods .................................................
end

# == Schema Information
#
# Table name: categories
#
#  id                      :bigint           not null, primary key
#  active                  :boolean          default(TRUE), not null
#  built_in                :boolean          default(FALSE), not null
#  card_transactions_count :integer          default(0), not null
#  card_transactions_total :integer          default(0), not null
#  cash_transactions_count :integer          default(0), not null
#  cash_transactions_total :integer          default(0), not null
#  category_name           :string           not null, uniquely indexed => [user_id]
#  colour                  :string           default("white"), not null
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  user_id                 :bigint           not null, indexed, uniquely indexed => [category_name]
#
# Indexes
#
#  index_categories_on_user_id           (user_id)
#  index_category_name_on_composite_key  (user_id,category_name) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  include TabsConcern
  include ContextHelper

  before_action :set_category, only: %i[edit update destroy]
  before_action :set_user_cards, :set_entities, :set_categories, only: %i[new create edit update]

  def index
    params[:include_inactive] ||= "false"
    conditions = { active: [ true, !JSON.parse(params[:include_inactive]) ] }

    @categories = current_user.categories.where(conditions).order(category_name: :asc)

    respond_to do |format|
      format.html

      format.turbo_stream do
        set_tabs(active_menu: :basic, active_sub_menu: :category)
      end
    end
  end

  def show; end

  def new
    @category = current_user.categories.new
  end

  def create
    index
    @category = Logic::Categories.create(category_params)

    if @category.active? && !@category.built_in?
      @card_transaction = Logic::CardTransactions.create_from(category: @category) if @category.valid?

      if @card_transaction
        set_user_cards
        set_categories
        set_tabs(active_menu: :card, active_sub_menu: @card_transaction.user_card.user_card_name)
      end
    end

    respond_to(&:turbo_stream)
  end

  def edit; end

  def update
    index
    @category = Logic::Categories.update(@category, category_params)

    if @category.active? && !@category.built_in?
      @card_transaction = Logic::CardTransactions.create_from(category: @category) if @category.valid?

      if @card_transaction
        set_user_cards
        set_categories
        set_tabs(active_menu: :card, active_sub_menu: @card_transaction.user_card.user_card_name)
      end
    end

    respond_to(&:turbo_stream)
  end

  def destroy
    @category.destroy if @category.card_transactions.empty? && @category.cash_transactions.empty? && @category.investments.empty?
    index

    respond_to(&:turbo_stream)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = current_user.categories.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:category_name, :colour, :active, :user_id)
  end
end

app/views/categories/category/_category.html.erb
<%= content_tag :div,
                class: "grid grid-cols-7 border-b border-slate-200 #{cycle('bg-gray-100', 'bg-gray-200')} hover:bg-white",
                data: { id: category.id, datatable_target: :row } do %>

    <div class="col-span-2 px-1 flex items-center mx-auto font-lekton font-semibold">
      <%= content_tag :span, category.name, class: "px-4 whitespace-nowrap border-0 rounded-sm shadow-md #{category.bg_colour} #{category.text_colour}" %>
    </div>

    <div class="jump_to_card_transactions px-1 flex items-center justify-center font-anonymous font-semibold whitespace-nowrap text-md">
      <% if category.card_transactions_count > 0 %>
        <%= link_to category.card_transactions_count,
                    search_card_transactions_path(card_transaction: { category_id: category.id }, all_month_years: true, format: :turbo_stream),
                    class: "text-indigo-600 hover:underline",
                    data: { turbo_frame: :center_container, turbo_prefetch: false } %>
      <% else %>
        <%= content_tag :span, category.card_transactions_count %>
      <% end %>
    </div>

    <div class="flex items-center justify-center font-lekton font-normal text-lg whitespace-nowrap">
      <%= content_tag :span, from_cent_based_to_float(category.card_transactions_total, "R$") %>
    </div>

    <div class="jump_to_cash_transactions px-1 flex items-center justify-center font-anonymous font-semibold whitespace-nowrap text-md">
      <% if category.cash_transactions_count > 0 %>
        <%= link_to category.cash_transactions_count,
                    cash_transactions_path(cash_transaction: { category_id: category.id }, all_month_years: true, format: :turbo_stream),
                    class: "text-indigo-600 hover:underline",
                    data: { turbo_frame: :center_container, turbo_prefetch: false } %>
      <% else %>
        <%= content_tag :span, category.cash_transactions_count %>
      <% end %>
    </div>

    <div class="flex items-center justify-center font-lekton font-normal text-lg whitespace-nowrap">
      <%= content_tag :span, from_cent_based_to_float(category.cash_transactions_total, "R$") %>
    </div>

    <div class="flex items-center justify-center">
      <div class="flex items-center justify-center px-2 my-1 rounded-md">
        <%= link_to edit_category_path(category),
                    id: "edit_category_#{category.id}",
                    class: "text-blue-600 hover:text-blue-800 mx-2 bg-sky-200 rounded-4xl",
                    data: { turbo_frame: :center_container } do %>
          <%= render_icon :pencil %>
        <% end %>

        <% if category.built_in == false %>
          <%= link_to category,
                      id: "delete_category_#{category.id}",
                      class: "text-red-600 hover:text-red-800 mx-2 bg-rose-200 rounded-4xl",
                      data: { turbo_method: :delete, turbo_confirm: t("confirmation.sure") } do %>
            <%= render_icon :destroy %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>

app/views/categories/category/_mobile_category.html.erb
<%= content_tag :div, class: "rounded-lg shadow-sm overflow-hidden my-3", data: { id: category.id, datatable_target: :row } do %>
  <%= content_tag :div, class: "p-4 bg-gradient-to-r #{category.from_bg} #{category.via_bg} to-white #{category.text_colour}" do %>
    <div class="flex items-center justify-between">
      <div class="flex items-center space-x-3">
        <%= render_icon :category %>
        <%= link_to category.name,
                    edit_category_path(category),
                    id: "edit_category_#{category.id}",
                    class: "text-lg font-semibold text-black underline underline-offset-[3px]",
                    data: { turbo_frame: :center_container } %>
      </div>
    </div>
  <% end %>

  <div class="p-4">
    <div class="grid grid-cols-2 gap-4 my-2">
      <div class="space-y-1">
        <%= content_tag :div, class: "flex items-center text-sm font-medium text-slate-500" do %>
          <%= render_icon :number %>
          <%= content_tag :span, pluralise_model(CardTransaction, 2), class: "ml-2" %>
        <% end %>

        <div class="flex items-center">
          <%= content_tag :span, category.card_transactions_count, class: "text-sm font-semibold text-slate-800" %>
        </div>
      </div>

      <div class="space-y-1">
        <div class="flex items-center space-x-2">
          <%= render_icon :money %>
          <%= content_tag :span, model_attribute(CardTransaction, :total_amount), class: "text-sm font-medium text-slate-500" %>
        </div>

        <div class="flex items-center">
          <%= content_tag :span, from_cent_based_to_float(category.card_transactions_total, "R$"), class: "text-sm font-semibold text-slate-800 mr-auto" %>

          <%= link_to search_card_transactions_path(card_transaction: { category_id: category.id }, all_month_years: true, format: :turbo_stream),
                      class: "my-auto mt-[-1rem]",
                      data: { turbo_frame: :center_container } do %>
            <%= render_icon :jump_to %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="grid grid-cols-2 gap-4 my-2">
      <div class="space-y-1">
        <%= content_tag :div, class: "flex items-center text-sm font-medium text-slate-500" do %>
          <%= render_icon :number %>
          <%= content_tag :span, pluralise_model(CashTransaction, 2), class: "ml-2" %>
        <% end %>

        <div class="flex items-center">
          <%= content_tag :span, category.cash_transactions_count, class: "text-sm font-semibold text-slate-800" %>
        </div>
      </div>

      <div class="space-y-1">
        <div class="flex items-center space-x-2">
          <%= render_icon :money %>
          <%= content_tag :span, model_attribute(CashTransaction, :total_amount), class: "text-sm font-medium text-slate-500" %>
        </div>

        <div class="flex items-center">
          <%= content_tag :span, from_cent_based_to_float(category.cash_transactions_total, "R$"), class: "text-sm font-semibold text-slate-800 mr-auto" %>

          <%= link_to cash_transactions_path(cash_transaction: { category_id: category.id }, all_month_years: true, format: :turbo_stream),
                      class: "my-auto mt-[-1rem]",
                      data: { turbo_frame: :center_container } do %>
            <%= render_icon :jump_to %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>