config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users
  patch "/locale", to: "users#update_locale", as: :update_locale

  # devise_for :users, controllers: {
  #   confirmations: "users/confirmations"
  # }

  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  resources :lalas do
    collection do
      get :card_transactions
      get :card_transactions_month_year

      get :cash_transactions
      get :cash_transactions_month_year
    end
  end

  resources :pages, only: :index do
    collection do
      get :donation
      get :notification
    end
  end

  resources :user_cards, except: :show
  resources :user_bank_accounts, except: :show
  resources :categories, except: :show
  resources :entities, except: :show
  resources :balances, only: :index do
    get :json, on: :collection
  end

  resources :cash_transactions, except: :show do
    collection do
      get :month_year
      get :inspect
    end
  end

  resources :card_transactions, except: :show do
    member do
      get :duplicate
    end

    collection do
      get :month_year
      get :search
      post :pay_in_advance
    end
  end

  resources :cash_installments, only: [] do
    member do
      patch :pay
    end

    collection do
      post :pay_multiple
    end
  end

  resources :investments, except: :show do
    collection do
      get :month_year
    end
  end

  resources :budgets, except: :show do
    collection do
      get :month_year
    end
  end

  namespace :admin do
    get :data_backup, to: "backups#data_backup"
  end

  root "pages#index"
end

app/models/entity.rb
# frozen_string_literal: true

class Entity < ApplicationRecord
  # @extends ..................................................................
  # @includes .................................................................
  include HasActive

  # @security (i.e. attr_accessible) ..........................................
  # @relationships ............................................................
  belongs_to :user

  has_many :entity_transactions, dependent: :destroy
  has_many :card_transactions, through: :entity_transactions, source: :transactable, source_type: "CardTransaction"
  has_many :cash_transactions, through: :entity_transactions, source: :transactable, source_type: "CashTransaction"

  # @validations ..............................................................
  validates :entity_name, presence: true, uniqueness: { scope: :user_id }

  # @callbacks ................................................................
  # @scopes ...................................................................
  # @additional_config ........................................................
  # @class_methods ............................................................
  # @public_instance_methods ..................................................
  def update_card_transactions_count_and_total
    update_columns(card_transactions_count: card_transactions.count, card_transactions_total: card_transactions.sum(:price))
  end

  def update_cash_transactions_count_and_total
    update_columns(cash_transactions_count: cash_transactions.count, cash_transactions_total: cash_transactions.sum(:price))
  end

  # @protected_instance_methods ...............................................
  # @private_instance_methods .................................................
end

# == Schema Information
#
# Table name: entities
#
#  id                      :bigint           not null, primary key
#  active                  :boolean          default(TRUE), not null
#  avatar_name             :string           default("people/0.png"), not null
#  card_transactions_count :integer          default(0), not null
#  card_transactions_total :integer          default(0), not null
#  cash_transactions_count :integer          default(0), not null
#  cash_transactions_total :integer          default(0), not null
#  entity_name             :string           not null, uniquely indexed => [user_id]
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  user_id                 :bigint           not null, indexed, uniquely indexed => [entity_name]
#
# Indexes
#
#  index_entities_on_user_id           (user_id)
#  index_entity_name_on_composite_key  (user_id,entity_name) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

app/controllers/entities_controller.rb
# frozen_string_literal: true

class EntitiesController < ApplicationController
  include TabsConcern
  include ContextHelper

  before_action :set_entity, only: %i[edit update destroy]
  before_action :set_user_cards, :set_entities, :set_categories, only: %i[new create edit update]

  def index
    params[:include_inactive] ||= "false"
    conditions = { active: [ true, !JSON.parse(params[:include_inactive]) ] }

    @entities = current_user.entities.where(conditions).order(entity_name: :asc)

    respond_to do |format|
      format.html

      format.turbo_stream do
        set_tabs(active_menu: :basic, active_sub_menu: :entity)
      end
    end
  end

  def show; end

  def new
    @entity = current_user.entities.new
  end

  def create
    index
    @entity = Logic::Entities.create(entity_params)

    if @entity.active?
      @card_transaction = Logic::CardTransactions.create_from(entity: @entity) if @entity.valid?

      if @card_transaction
        set_user_cards
        set_entities
        set_tabs(active_menu: :card, active_sub_menu: @card_transaction.user_card.user_card_name)
      end
    end

    respond_to(&:turbo_stream)
  end

  def edit; end

  def update
    index
    @entity = Logic::Entities.update(@entity, entity_params)

    if @entity.active?
      @card_transaction = Logic::CardTransactions.create_from(entity: @entity) if @entity.valid?

      if @card_transaction
        set_user_cards
        set_entities
        set_tabs(active_menu: :card, active_sub_menu: @card_transaction.user_card.user_card_name)
      end
    end

    respond_to(&:turbo_stream)
  end

  def destroy
    @entity.destroy if @entity.card_transactions.empty? && @entity.cash_transactions.empty?
    index

    respond_to(&:turbo_stream)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entity
    @entity = current_user.entities.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def entity_params
    params.require(:entity).permit(:entity_name, :active, :avatar_name, :user_id)
  end
end

app/views/entities/entity/_entity.html.erb
<%= content_tag :div,
                class: "grid grid-cols-8 border-b border-slate-200 #{cycle('bg-gray-100', 'bg-gray-200')} hover:bg-white",
                data: { id: entity.id, datatable_target: :row } do %>

    <div class="px-1 flex items-center justify-center">
    <%= image_tag asset_path("avatars/#{entity.avatar_name}"), class: "size-7 rounded-full" %>
    </div>

    <div class="col-span-2 px-1 text-center font-lekton font-semibold">
      <%= content_tag :span, entity.entity_name, class: "px-4 whitespace-nowrap" %>
    </div>

    <div class="jump_to_card_transactions px-1 flex items-center justify-center font-anonymous font-semibold whitespace-nowrap text-md">
      <% if entity.card_transactions_count > 0 %>
        <%= link_to entity.card_transactions_count,
                    search_card_transactions_path(card_transaction: { entity_id: entity.id }, all_month_years: true, format: :turbo_stream),
                    class: "text-indigo-600 hover:underline",
                    data: { turbo_frame: :center_container, turbo_prefetch: false } %>
      <% else %>
        <%= content_tag :span, entity.card_transactions_count %>
      <% end %>
    </div>

    <div class="flex items-center justify-center font-lekton font-normal text-lg whitespace-nowrap">
      <%= content_tag :span, from_cent_based_to_float(entity.card_transactions_total, "R$") %>
    </div>

    <div class="jump_to_cash_transactions px-1 flex items-center justify-center font-anonymous font-semibold whitespace-nowrap text-md">
      <% if entity.cash_transactions_count > 0 %>
        <%= link_to entity.cash_transactions_count,
                    cash_transactions_path(cash_transaction: { entity_id: entity.id }, all_month_years: true, format: :turbo_stream),
                    class: "text-indigo-600 hover:underline",
                    data: { turbo_frame: :center_container, turbo_prefetch: false } %>
      <% else %>
        <%= content_tag :span, entity.cash_transactions_count %>
      <% end %>
    </div>

    <div class="flex items-center justify-center font-lekton font-normal text-lg whitespace-nowrap">
      <%= content_tag :span, from_cent_based_to_float(entity.cash_transactions_total, "R$") %>
    </div>

    <div class="flex items-center justify-center">
      <div class="flex items-center justify-center px-2 my-1 rounded-md">
        <%= link_to edit_entity_path(entity),
                    id: "edit_entity_#{entity.id}",
                    class: "text-blue-600 hover:text-blue-800 mx-2 bg-sky-200 rounded-4xl",
                    data: { turbo_frame: :center_container } do %>
          <%= render_icon :pencil %>
        <% end %>

        <%= link_to entity,
                    id: "delete_entity_#{entity.id}",
                    class: "text-red-600 hover:text-red-800 mx-2 bg-rose-200 rounded-4xl",
                    data: { turbo_method: :delete, turbo_confirm: t("confirmation.sure") } do %>
          <%= render_icon :destroy %>
        <% end %>
      </div>
    </div>
  <% end %>

app/views/entities/entity/_mobile_entity.html.erb
<%= content_tag :div, class: "rounded-lg shadow-sm overflow-hidden my-3 bg-slate-100", data: { id: entity.id, datatable_target: :row } do %>
  <div class="p-4 bg-gradient-to-r from-slate-700 via-slate-400 to-white">
    <div class="flex items-center justify-between">
      <div class="flex items-center space-x-3">
        <%= image_tag asset_path("avatars/#{entity.avatar_name}"), class: "w-6 h-6 rounded-full" %>

        <%= link_to entity.entity_name,
                    edit_entity_path(entity),
                    id: "edit_entity_#{entity.id}",
                    class: "text-lg font-semibold text-black underline underline-offset-[3px]",
                    data: { turbo_frame: :center_container } %>
      </div>
    </div>
  </div>

  <div class="p-4">
    <div class="grid grid-cols-2 gap-4 my-2">
      <div class="space-y-1">
        <%= content_tag :div, class: "flex items-center text-sm font-medium text-slate-500" do %>
          <%= render_icon :number %>
          <%= content_tag :span, pluralise_model(CardTransaction, 2), class: "ml-2" %>
        <% end %>

        <div class="flex items-center">
          <%= content_tag :span, entity.card_transactions_count, class: "text-sm font-semibold text-slate-800" %>
        </div>
      </div>

      <div class="space-y-1">
        <div class="flex items-center space-x-2">
          <%= render_icon :money %>
          <%= content_tag :span, model_attribute(CardTransaction, :total_amount), class: "text-sm font-medium text-slate-500" %>
        </div>

        <div class="flex items-center">
          <%= content_tag :span, from_cent_based_to_float(entity.card_transactions_total, "R$"), class: "text-sm font-semibold text-slate-800 mr-auto" %>

          <%= link_to search_card_transactions_path(card_transaction: { entity_id: entity.id }, all_month_years: true, format: :turbo_stream),
                      class: "my-auto mt-[-1rem]",
                      data: { turbo_frame: :center_container } do %>
            <%= render_icon :jump_to %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="grid grid-cols-2 gap-4 my-2">
      <div class="space-y-1">
        <%= content_tag :div, class: "flex items-center text-sm font-medium text-slate-500" do %>
          <%= render_icon :number %>
          <%= content_tag :span, pluralise_model(CashTransaction, 2), class: "ml-2 truncate" %>
        <% end %>

        <div class="flex items-center">
          <%= content_tag :span, entity.cash_transactions_count, class: "text-sm font-semibold text-slate-800" %>
        </div>
      </div>

      <div class="space-y-1">
        <div class="flex items-center space-x-2">
          <%= render_icon :money %>
          <%= content_tag :span, model_attribute(CashTransaction, :total_amount), class: "text-sm font-medium text-slate-500" %>
        </div>

        <div class="flex items-center">
          <%= content_tag :span, from_cent_based_to_float(entity.cash_transactions_total, "R$"), class: "text-sm font-semibold text-slate-800 mr-auto" %>

          <%= link_to cash_transactions_path(cash_transaction: { entity_id: entity.id }, all_month_years: true, format: :turbo_stream),
                      class: "my-auto mt-[-1rem]",
                      data: { turbo_frame: :center_container } do %>
            <%= render_icon :jump_to %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>